### PR TITLE
DROOLS-6100 - Add PMML asset for clustering

### PR DESCRIPTION
**Pull request by jiripetrlik**

### CODE REVIEW

**Comment by jstastny-cz** [comment]
Please try to rebase.

**Comment by jiripetrlik** [comment]
@jstastny-cz 
Rebased, but there is still some unexpected exception in PR check. Will try to look at it more tomorrow.

**Comment by jstastny-cz** [comment]
Please try one more rebase.

**Comment by jiripetrlik** [comment]
@jstastny-cz 
Hello it seems that PR check is finally green. Can we merge now?

**Pull request merged**
